language: cpp
compiler: gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y scons python-jinja2
before_script:
 - sudo apt-get install -y software-properties-common
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get update -q
 - sudo apt-get install -y gcc-arm-none-eabi
script:
 - cd source
 - scons
